create or replace PACKAGE CEN_OCS_FORM19 AS 

PROCEDURE FETCH_FORM_19_CLAIM_DTLS	
( 
    IN_TRACKING_ID      IN CEN_OCS_FORM_19.TRACKING_ID%TYPE,
    OUT_CLAIM_DTLS      OUT COMM_TYPE_DECLARATIONS_WB.REF_CURSOR_TYPE,
	OUT_MESSAGE OUT VARCHAR2,
    OUT_STATUS OUT NUMBER
);

PROCEDURE CHANGE_CLAIM_STATUS
(
    IN_TRACKING_ID      IN CEN_OCS_FORM_19.TRACKING_ID%TYPE
);


PROCEDURE INSERT_IN_PYMT_CLAIM_DTLS
(
    IN_TRACKING_ID              IN CEN_PYMT_CLAIM_DTLS.TRACKING_ID%TYPE,
    IN_UAN                      IN CEN_PYMT_CLAIM_DTLS.UAN%TYPE,
    IN_MEMBER_ID                IN CEN_PYMT_CLAIM_DTLS.MEMBER_ID%TYPE,
    IN_MEMBER_NAME              IN CEN_PYMT_CLAIM_DTLS.MEMBER_NAME%TYPE,
    IN_ESTABLISHMENT_ID         IN CEN_PYMT_CLAIM_DTLS.ESTABLISHMENT_ID%TYPE,
    IN_PAYMENT_APPROVAL_DATE    IN CEN_PYMT_CLAIM_DTLS.PAYMENT_APPROVAL_DATE%TYPE,
    IN_OFFICE_CODE              IN CEN_PYMT_CLAIM_DTLS.OFFICE_CODE%TYPE,
    IN_IFSC_CODE                IN CEN_PYMT_CLAIM_DTLS.IFSC_CODE%TYPE,
    IN_SESSION_ID               IN CEN_PYMT_CLAIM_DTLS.SESSION_ID%TYPE    
);

PROCEDURE GET_PDF_15GH
(
    IN_TRACKING_ID      IN CEN_OCS_FORM_19.TRACKING_ID%TYPE,
    OUT_PDF_15GH        OUT VARCHAR
);

PROCEDURE CHANGE_CLAIM_STATUS_REJECT
(
    IN_TRACKING_ID      IN CEN_OCS_FORM_19.TRACKING_ID%TYPE,
    IN_LATEST_REMARK    IN CEN_OCS_FORM_19.LATEST_REMARK%TYPE
);

PROCEDURE CHANGE_LATEST_APP_STATUS_NE
(
    IN_TRACKING_ID      IN CEN_OCS_FORM_19.TRACKING_ID%TYPE,
    IN_REMARK           IN CEN_OCS_FORM_19.LATEST_REMARK%TYPE
);

PROCEDURE GET_REJECTION_REASON (
    OUT_REJECTION_REASON OUT COMM_TYPE_DECLARATIONS_WB.REF_CURSOR_TYPE
);


--////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
-- new modification -- procedure for user management
-- modification date 27/09/2023

procedure GET_ESTABLISHMENT_AND_PG_ID(
        IN_USER_ID       in   number,
        IN_OFFICE_ID     in   number,
        IN_PROCESS_ID    in   fo_auth_process.process_id%type,
        IN_PROCESS_NAME  in   fo_auth_process.process_name%type,
        OUT_EST_P_FLOW   out  COMM_TYPE_DECLARATIONS_WB.REF_CURSOR_TYPE
);

PROCEDURE GET_TRACKING_IDS
(
  IN_PROCESS_GROUP_ID IN NUMBER,
  IN_ESTABLISHMENT_ID IN VARCHAR2,
  IN_ACTOR_ID NUMBER,
  IN_EST_GROUPID IN NUMBER,
  IN_OFFICE_ID IN NUMBER,
  IN_USER_ID IN NUMBER,
  IN_CLAIM_MODE IN   CHAR,
  OUT_T_ID_LIST OUT COMM_TYPE_DECLARATIONS_WB.REF_CURSOR_TYPE
);

procedure GET_USER_ID 
( 
    IN_ACTOR_LEVEL      IN NUMBER,
    IN_TRACKING_ID      IN CEN_OCS_FORM_19.TRACKING_ID%TYPE,
    IN_GROUP_TYPE       IN VARCHAR2,
    IN_MEMBER_ID        IN VARCHAR2,
    OUT_USER_ID         OUT VARCHAR2
);

PROCEDURE GET_LEVEL_OF_USER(
        IN_USER_ID       IN   FO_OFFICE_USERS.id%type,
        IN_OFFICE_ID     IN   CEN_OCS_FORM_20.OFFICE_ID%type,
        IN_CRITERIA_ID   IN   NUMBER,
        IN_MEMBER_ID     IN   VARCHAR2,
        OUT_ACTOR_LEVEL  OUT  VARCHAR2
 );

procedure GET_PROCESS_FLOW 
( 
    IN_CRITERIA_ID IN CEN_OCS_FORM_19.CRITERIA_ID%TYPE,
    IN_PROCESS_ID IN FO_AUTH_PROCESS_FLOW.PROCESS_ID%TYPE,
    IN_CRITERIA_FLOW_ID IN CEN_OCS_FORM_19.CRITERIA_FLOW_ID%TYPE,
    OUT_PROCESS_FLOW  out  COMM_TYPE_DECLARATIONS_WB.REF_CURSOR_TYPE
);
 
procedure GET_CURRENT_FLOW 
( 
    IN_CRITERIA_ID      IN FO_AUTH_PROCESS_FLOW.CRITERIA_ID%TYPE,
    IN_PROCESS_ID       IN FO_AUTH_PROCESS_FLOW.PROCESS_ID%TYPE,
    IN_CRITERIA_FLOW_ID IN FO_AUTH_PROCESS_FLOW.CRITERIA_FLOW_ID%TYPE,
    IN_FROM_ACTOR       IN FO_AUTH_PROCESS_FLOW.FROM_ACTOR%TYPE,
    IN_GROUP_TYPE       IN FO_AUTH_PROCESS_FLOW.GROUP_TYPE%TYPE,
    OUT_CURRENT_FLOW  out  COMM_TYPE_DECLARATIONS_WB.REF_CURSOR_TYPE
);

PROCEDURE GET_PROCESS_FLOW_BY_GROUP 
(
    IN_CRITERIA_ID      IN CEN_OCS_FORM_19.CRITERIA_ID%TYPE,
    IN_PROCESS_ID       IN FO_AUTH_PROCESS_FLOW.PROCESS_ID%TYPE,
    IN_CRITERIA_FLOW_ID IN CEN_OCS_FORM_19.CRITERIA_FLOW_ID%TYPE,
    IN_GROUP_TYPE       IN FO_AUTH_PROCESS_FLOW.GROUP_TYPE%TYPE,
    OUT_PROCESS_FLOW    OUT  COMM_TYPE_DECLARATIONS_WB.REF_CURSOR_TYPE
);

PROCEDURE UPDATE_LAS_AND_NEXT_USER(
    IN_APPROVAL_STATUS IN CEN_OCS_FORM_19.LATEST_APPROVAL_STATUS%TYPE,
    IN_TRACKING_ID IN CEN_OCS_FORM_19.TRACKING_ID%TYPE,
    IN_NEXT_USER IN CEN_OCS_FORM_19.NEXT_USER_ID%TYPE,
    IN_LATEST_REMARK    IN CEN_OCS_FORM_19.LATEST_REMARK%TYPE,
    OUT_STATUS OUT NUMBER
);


END CEN_OCS_FORM19;